accounts/urls.py
from django.urls import path
from accounts import views
import allauth.account.views as ahv

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('login/', views.LoginView.as_view(), name='account_login'),
    path('logout/', views.LogoutView.as_view(), name='account_logout'),
    path('signup/', views.SignupView.as_view(), name='account_signup'),

    path('password_reset/', views.ResetPassword.as_view(), name='reset_password'),
    path('password_reset_done/', views.ResetPasswordSent.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', views.ResetPasswordConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.ResetPasswordComplete.as_view(), name='password_reset_complete'),

]

app/urls.py
from django.urls import path
from app import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('product/<slug>', views.ItemDetailView.as_view(), name='product'),
    path('additem/<slug>', views.addItem, name='additem'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('remove/<slug>', views.removeItem, name='removeitem'),
    path('removesingleitem/<slug>', views.removeSingleItem, name='removesingleitem'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('favorited/', views.FavoriteView.as_view(), name='favorited'),
    path('favorite/<slug>', views.favorite, name='favorite'),
]

logosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager, PermissionsMixin
from django.utils import timezone


class UserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)
    

class CustomUser(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField('Email', unique=True)
    first_name = models.CharField('first_name', max_length=150)
    last_name = models.CharField('last_name', max_length=150)
    tel = models.CharField('telephone', max_length=30, blank=True)
    created = models.DateTimeField('entry_date', default=timezone.now)
    is_staff = models.BooleanField(
        ("staff status"),
        default=False,
        help_text=("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        ("active"),
        default=True,
        help_text=(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = ("user")
        verbose_name_plural = ("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

accounts/forms.py
from django import forms
from allauth.account.forms import SignupForm
import re


class ProfileForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First name')
    last_name = forms.CharField(max_length=30, label='Last name')
    tel = forms.CharField(max_length=30, label='telephone', required=False)


class SignupUserForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First name')
    last_name = forms.CharField(max_length=30, label='Last name')
    tel = forms.CharField(max_length=30, label='telephone', required=False)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        email_pattern = re.compile(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$')
        if not email_pattern.match(email):
            raise forms.ValidationError('Enter a valid email')
        return email
    
    def clean_tel(self):
        tel = self.cleaned_data.get('tel')
        pattern = re.compile(r'^\d+$')
        if not pattern.match(tel):
            raise forms.ValidationError('Enter a valid number')
        return tel

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Password does not match')
        return password2


    def save(self, request):
        user = super(SignupUserForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.tel = self.cleaned_data['tel']
        user.save()
        return user

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from accounts.models import CustomUser
from accounts.forms import ProfileForm, SignupUserForm
from allauth.account import views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views


class ProfileView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_data = CustomUser.objects.get(id=request.user.id)
        return render(request, 'accounts/profile.html', {
            'user_data': user_data,
        })
    
class ProfileEditView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_data = CustomUser.objects.get(id=request.user.id)
        form = ProfileForm(
            request.POST or None,
            initial = {
                'first_name': user_data.first_name,
                'last_name': user_data.last_name,
                'tel': user_data.tel,
            }
        )
        return render (request, 'accounts/profile_edit.html', {
            'form': form
        })
    
    def post(self, request, *args, **kwargs):
        form = ProfileForm(request.POST or None)
        if form.is_valid():
            user_data = CustomUser.objects.get(id=request.user.id)
            user_data.first_name = form.cleaned_data['first_name']
            user_data.last_name = form.cleaned_data['last_name']
            user_data.tel = form.cleaned_data['tel']
            user_data.save()
            return redirect('profile')

        return render(request, 'accounts/profile.html', {
            'form': form
        })
    
class LoginView(views.LoginView):
    template_name = 'accounts/login.html'


class LogoutView(views.LogoutView):
    template_name = 'accounts/logout.html'

    def post (self, *args, **kwargs):
        if self.request.user.is_authenticated:
            self.logout()
        return redirect('/')
    

class SignupView(views.SignupView):
    template_name = 'accounts/signup.html'
    form_class = SignupUserForm


class ResetPassword(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset.html'

class ResetPasswordSent(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_sent.html'

class ResetPasswordConfirm(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_form.html'

class ResetPasswordComplete(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_done.html'

accounts/templates/accounts/login.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock %}

{% block content %}

<div class="signup">
    <h5>Login</h5>
    <form method='post' class="form">
        {% csrf_token %}
        <div class="email">
            {% render_field form.login class='form-control' placeholder='Email' %}
        </div>
        <div class="password">
            {% render_field form.password class='form-control' placeholder='Password' %}
        </div>
        <div class="change">
            <a href="{% url 'reset_password' %}">Forgot password?</a>
        </div>
        <div class="confirm">
            <button class="btn" type="submit">Login</button>
        </div>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'app/base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/logout.css' %}">
{% endblock %}

{% block content %}

<div class="logout">
    <p>Are you Logout?</p>
    <form method="post" class="form">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'app/base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
{% endblock %}

{% block content %}

<div class="container">
    <h3>Please enter your email to change password</h3>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="Submit" name="Send email">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'app/base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
{% endblock %}

{% block content %}

<div class="container">
    <h3>Password reset completed</h3>
    <a href="/" class="btn">Login</a>
</div>


{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends 'app/base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
{% endblock %}


{% block content %}

<div class="container">
    <h3>Reset Your Password</h3>
    <form method="post">
      {% csrf_token %}
      
      {% for error in form.errors %}
        <p class="error-message">{{ error }}</p>
      {% endfor %}

      {{ form.new_password1.label_tag }}
      {{ form.new_password1 }}
      
      {{ form.new_password2.label_tag }}
      {{ form.new_password2 }}
      
      <input type="submit" value="Reset Password">
    </form>
  </div>

{% endblock %}

accounts/templates/accounts/password_reset_sent.html
{% extends 'app/base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
{% endblock %}


{% block content %}

<h3>We've sent you instructions for change your password.</h3>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'app/base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}

<div class="container">
    <div class="profile">
        <h5 class="title">Profile</h5>
        <table class="info">
            <tbody>
                <tr>
                    <th class="header">Name</th>
                    <td class="data">{{ user_data.first_name }} {{ user_data.last_name }}</td>
                </tr>
                <tr>
                    <th class="header">Email</th>
                    <td class="data">{{ user_data.email }}</td>
                </tr>
                <tr>
                    <th class="header">Telephone</th>
                    <td class="data">{{ user_data.tel }}</td>
                </tr>
                <tr>
                    <th class="header">Entry date</th>
                    <td class="data">{{ user_data.created }}</td>
                </tr>
            </tbody>
        </table>
        <div class="edit">
            <a href="{% url 'profile_edit' %}">Edit</a>
        </div>
    </div>
    <div class="product">
        {% for order_item in order_items %}
            <li>{{ order_item.item.nome }} - Quantidade: {{ order_item.quantity }}</li>
        {% endfor %}
    </div>
</div>

{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}

<div class="container">
    <h5 class="title">Profile</h5>
    <form action="{% url 'profile_edit' %}" method="post">
        {% csrf_token %}
        <table class="info">
            <tbody>
                <tr>
                    <th class="header">Name</th>
                    <td class="data">
                        {% render_field form.first_name class='form-control' placeholder='性' %}
                        {% render_field form.last_name class='form-control' placeholder='名' %}
                    </td>
                </tr>
                <tr>
                    <th class="header">Telephone</th>
                    <td class="data">
                        {% render_field form.tel class='form-control' placeholder='Telephone' %}
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="btn">
            <button class="save">Save</button>
        </div>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock %}

{% block content %}

<div class="signup">
    <h5>Signup</h5>
    <form method="post" class="form">
        {% csrf_token %}
        <div class="name">
            {% render_field form.first_name class='form-control' placeholder='First name' id='id_first_name' %}
            {% render_field form.last_name class='form-control' placeholder='Last name' id='id_last_name' %}
        </div>
        <div class="email">
            {% render_field form.email class='form-control' placeholder='Email' id='id_email' %}
            {% if form.email.errors %}
                <div class="error">*{{ form.email.errors.0 }}</div>
            {% endif %}
        </div>
        <div class="tel">
            {% render_field form.tel class='form-control' placeholder='Telephone' id='id_tel' %}
            {% if form.tel.errors %}
                <div class="error">*{{ form.tel.errors.0 }}</div>
            {% endif %}
        </div>
        <div class="pass1">
            {% render_field form.password1 class='form-control' placeholder='Password' id='id_password1' %}
            {% if form.password1.errors %}
                <div class="error">*{{ form.password1.errors.0 }}</div>
            {% endif %}
        </div>
        <div class="pass2">
            {% render_field form.password2 class='form-control' placeholder='Confirm password' id='id_password2' %}
            {% if form.password2.errors %}
                <div class="error">*{{ form.password2.errors.0 }}</div>
            {% endif %}
        </div>
        <div class="confirm">
            <button class="btn" type="submit">Signup</button>
        </div>
    </form>
</div>

{% endblock %}